name: "PyGloTarAn examples"
description: "Run pyglotaran examples as integration test against a version of glotaran"
author: "Sebastian Weigand"
inputs:
  example_name:
    description: "Which example to run {quick-start, fluorescence, spectral-constraints, two-datasets, sim-3d-disp, sim-3d-nodisp, sim-3d-weight, sim-6d-disp, run-all}"
    required: true
  examples_branch:
    description: "Branch/tag of pyglotaran examples to use"
    required: true
    default: main

outputs:
  plots-path:
    description: "Plot result path of example run"
    value: ${{ steps.example-run.outputs.plots-path }}

runs:
  using: "composite"
  steps:
    - name: Clone pyglotaran-examples to pyglotaran-examples
      run: |
        [ ! -d pyglotaran-examples ] && [ ! -n '${{ inputs.examples_branch }}' ] && \
          { \
            echo "::error:: Branch not provided and 'pyglotaran-examples' folder doesn't exist.\
            Manually clone the examples repo to 'pyglotaran-examples' if you use it with the 'push' or 'pull_request' event."; \
            exit 1; \
          }
        echo "::group:: Cloning examples branch '${{ inputs.examples_branch }}' to pyglotaran-examples"
        [ ! -d pyglotaran-examples ] && \
          git clone  --depth 1 -b ${{ inputs.examples_branch }} https://github.com/glotaran/pyglotaran-examples.git || \
          echo "Folder pyglotaran-examples already exists, skipping cloning."
        echo "::endgroup::"
      shell: bash
    - name: Install pyglotaran-examples
      run: |
        echo "::group:: Installing pyglotaran-examples"
        pip install wheel
        pip install -e ./pyglotaran-examples
        echo "::endgroup::"
      shell: bash
    - name: Install additional requirements
      run: |
        echo "::group:: Installing requirements"
        pip install -r pyglotaran-examples/requirements.txt
        echo "::endgroup::"
      shell: bash
    - name: Run example
      id: example-run
      run: |
        echo "::group:: Running ${{ inputs.example_name }}"
        python pyglotaran-examples/scripts/run_examples.py ${{ inputs.example_name }} --headless 2>&1
        echo "::set-output name=plots-path::pyglotaran-examples/plot_results"
        echo "::endgroup::"
      shell: bash
