[tool.black]
line-length = 99
target-version = ['py38']
exclude = '''
/(
    \.eggs
  | \.git
  | \.hg
  | \.mypy_cache
  | \.tox
  | \.venv
  | _build
  | buck-out
  | build
  | dist
)/
'''

[tool.isort]
profile = "hug"
src_paths = ["pyglotaran_examples", "scripts"]
include_trailing_comma = true
line_length = 99
force_single_line = true
remove_redundant_aliases = true

[tool.nbqa.addopts]
flake8 = [
    "--extend-ignore=E402,F404"
]
