input:
  - ["1", 1]
  - ["0", 0]
  - {vary: false}

irf:
  - ["center", -83.0]
  - ["width", 1.5]
  - ["backsweep", 13200.0, {vary: false}]

kinetic:
  - 0.2
  - 0.07
  - 0.02
  - 0.00016
  - {non-negative: true}
