input:
  - ["1", 1]
  - ["0", 0]
  - {vary: false}

irf:
  - ["center", -83.0]
  - ["width", 1.5]
  - ["backsweep", 13200.0, {vary: false}]

rates:
  - ["bulk_to_red1", 0.2]
  - ["red1_to_red2", 0.07]
  - ["red2_to_free", 0.02]
  - ["free_out", 0.00016]
  - {non-negative: true}
